export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const SELECT_NOTE = "SELECT_NOTE";
export const UPDATE_NOTE_LIST = "UPDATE_NOTE_LIST";
export const UPDATE_NOTE_BEING_MODIFIED = "UPDATE_NOTE_BEING_MODIFIED";